import { assetStore } from "@/src/database/assetStore";
import type { MapDocument } from "@/src/types/domain";

const escapeXml=(value:string)=>value.replace(/[<>&'"]/g,char=>({"<":"&lt;",">":"&gt;","&":"&amp;","'":"&apos;",'"':"&quot;"}[char]!));
const asDataUrl=(blob:Blob)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)});
const iconSymbols:Record<string,string>={lightbulb:"💡",star:"★",check:"✓",warning:"⚠",book:"▤",code:"</>",target:"◎",flag:"⚑",heart:"♥",bookmark:"▮",calendar:"▦",briefcase:"▣"};

function bounds(doc:MapDocument){const pad=80;const minX=Math.min(...doc.nodes.map(n=>n.x))-pad,minY=Math.min(...doc.nodes.map(n=>n.y))-pad,maxX=Math.max(...doc.nodes.map(n=>n.x+n.width))+pad,maxY=Math.max(...doc.nodes.map(n=>n.y+n.height))+pad;return{minX,minY,width:Math.max(1,maxX-minX),height:Math.max(1,maxY-minY)}}

export async function mapToSvg(doc:MapDocument){
  const box=bounds(doc);const byId=new Map(doc.nodes.map(n=>[n.id,n]));const imageData=new Map<string,string>();
  for(const asset of doc.assets){const blob=await assetStore.blob(asset);if(blob)imageData.set(asset.id,await asDataUrl(blob))}
  const edges=doc.nodes.filter(n=>n.parentId&&byId.has(n.parentId)).map(n=>{const p=byId.get(n.parentId!)!;return`<path d="M ${p.x+p.width} ${p.y+p.height/2} C ${p.x+p.width+80} ${p.y+p.height/2}, ${n.x-80} ${n.y+n.height/2}, ${n.x} ${n.y+n.height/2}" fill="none" stroke="${escapeXml(n.branchColor??"#53677e")}" stroke-width="2"/>`}).join("");
  const independent=doc.connections.map(c=>{const s=byId.get(c.sourceId),t=byId.get(c.targetId);return s&&t?`<path d="M ${s.x+s.width/2} ${s.y+s.height/2} L ${t.x+t.width/2} ${t.y+t.height/2}" fill="none" stroke="${escapeXml(c.color)}" stroke-width="2" stroke-dasharray="7 5"/>`:""}).join("");
  const nodes=doc.nodes.map(n=>{const bindings=doc.nodeAssets.filter(b=>b.nodeId===n.id);const images=bindings.map((binding,index)=>{const src=imageData.get(binding.assetId);return src?`<image href="${src}" x="${n.x+8}" y="${n.y+7+index*55}" width="${Math.min(binding.width,n.width-16)}" height="${Math.min(binding.height,52)}" preserveAspectRatio="xMidYMid ${binding.objectFit==='cover'?'slice':'meet'}"/>`:""}).join("");const textY=n.y+(bindings.length?Math.min(60,bindings.length*55):0)+n.height/2;const lines=n.text.split("\n");const align=n.textAlign??"left",textX=align==="center"?n.x+n.width/2:align==="right"?n.x+n.width-14:n.x+14,anchor=align==="center"?"middle":align==="right"?"end":"start",font=n.fontFamily==="serif"?"Georgia,serif":n.fontFamily==="mono"?"monospace":"Arial,sans-serif",prefix=`${n.icon?`${iconSymbols[n.icon]??""} `:""}${n.emoji?`${n.emoji} `:""}`;return`<g><rect x="${n.x}" y="${n.y}" width="${n.width}" height="${Math.max(n.height,bindings.length?125:n.height)}" rx="10" fill="${escapeXml(n.background)}" stroke="${escapeXml(n.borderColor)}"/><text x="${textX}" y="${textY}" fill="${escapeXml(n.color)}" font-family="${font}" font-size="${n.fontSize??13}" font-weight="${n.fontWeight??590}" font-style="${n.fontStyle??"normal"}" text-decoration="${n.textDecoration??"none"}" text-anchor="${anchor}">${lines.map((line,i)=>`<tspan x="${textX}" dy="${i?(n.fontSize??13)+4:0}">${escapeXml(prefix+line)}</tspan>`).join("")}</text>${images}</g>`}).join("");
  return`<svg xmlns="http://www.w3.org/2000/svg" width="${box.width}" height="${box.height}" viewBox="${box.minX} ${box.minY} ${box.width} ${box.height}"><rect x="${box.minX}" y="${box.minY}" width="${box.width}" height="${box.height}" fill="#0c0e12"/>${edges}${independent}${nodes}</svg>`;
}

export async function exportVisual(doc:MapDocument,format:"svg"|"png"|"pdf"){
  const svg=await mapToSvg(doc);if(format==="svg"){saveBlob(new Blob([svg],{type:"image/svg+xml"}),`${slug(doc.mindmap.title)}.svg`);return}
  const url=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"}));const image=new Image();await new Promise<void>((resolve,reject)=>{image.onload=()=>resolve();image.onerror=()=>reject(new Error("Could not render map"));image.src=url});const scale=Math.min(2,4096/Math.max(image.width,image.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,image.width*scale);canvas.height=Math.max(1,image.height*scale);canvas.getContext("2d")!.drawImage(image,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);if(format==="png"){canvas.toBlob(blob=>blob&&saveBlob(blob,`${slug(doc.mindmap.title)}.png`),"image/png");return}const{jsPDF}=await import("jspdf");const orientation=canvas.width>=canvas.height?"landscape":"portrait";const pdf=new jsPDF({orientation,unit:"px",format:[canvas.width,canvas.height],hotfixes:["px_scaling"]});pdf.addImage(canvas.toDataURL("image/png"),"PNG",0,0,canvas.width,canvas.height);pdf.save(`${slug(doc.mindmap.title)}.pdf`)
}

export async function exportPortable(doc:MapDocument){const{default:JSZip}=await import("jszip");const zip=new JSZip();zip.file("manifest.json",JSON.stringify({format:"luma-mindmap",version:1,createdAt:Date.now()},null,2));zip.file("map.json",JSON.stringify(doc,null,2));for(const asset of doc.assets){const blob=await assetStore.blob(asset);if(blob)zip.file(asset.storagePath,blob)}saveBlob(await zip.generateAsync({type:"blob",compression:"DEFLATE"}),`${slug(doc.mindmap.title)}.mindmap`)}
export async function importPortable(file:File){const{default:JSZip}=await import("jszip");const zip=await JSZip.loadAsync(file);const manifest=JSON.parse(await zip.file("manifest.json")!.async("text")) as {format:string;version:number};if(manifest.format!=="luma-mindmap"||manifest.version!==1)throw new Error("Unsupported mind map package");const doc=JSON.parse(await zip.file("map.json")!.async("text")) as MapDocument;for(const asset of doc.assets){const entry=zip.file(asset.storagePath);if(!entry)continue;const blob=await entry.async("blob");const restored=new File([blob],asset.fileName,{type:asset.mimeType});const stored=await assetStore.write(restored,doc.mindmap.id,[]);asset.storagePath=stored.storagePath;asset.hash=stored.hash}return doc}
function saveBlob(blob:Blob,name:string){const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=name;link.click();URL.revokeObjectURL(link.href)}
const slug=(value:string)=>value.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"mind-map";
