"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Command, Database, Download, FilePlus2, HardDrive, LayoutPanelLeft, Link2, Moon, Search, Settings, Trash2, Upload, X } from "lucide-react";
import { Dashboard } from "./Dashboard";
import { Editor } from "./Editor";
import { autoLayout } from "@/src/lib/layout";
import { createMapDocument, createWelcomeDocument } from "@/src/lib/seed";
import { localDatabase } from "@/src/database/repository";
import { id, type Asset, type ColorRole, type MapDocument, type MindmapNode, type NodeAsset, type RecentColors } from "@/src/types/domain";
import { assetStore } from "@/src/database/assetStore";
import { exportPortable, exportVisual, importPortable } from "@/src/lib/exporters";
import { createNodeFromReference, EMPTY_RECENT_COLORS, registerRecentColor } from "@/src/lib/editorFeatures";

const normalize = (doc: MapDocument): MapDocument => ({ ...doc, tags: doc.tags ?? [], assets: doc.assets ?? [], nodeAssets: doc.nodeAssets ?? [], connections: doc.connections ?? [],nodes:doc.nodes.map(node=>({...node,elementKind:node.elementKind??"node",richText:node.richText??[node.description,node.notes].filter(Boolean).map(text=>`<p>${text.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\n/g,"<br>")}</p>`).join("")})) });

export default function App() {
  const [documents, setDocuments] = useState<MapDocument[]>([]);
  const [activeId, setActiveId] = useState<string | null>(null);
  const [selected, setSelected] = useState<string[]>([]);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [zoom, setZoom] = useState(1);
  const [pan, setPan] = useState({ x: 470, y: 360 });
  const [ready, setReady] = useState(false);
  const [saved, setSaved] = useState(true);
  const [overlay, setOverlay] = useState<"commands" | "shortcuts" | "search" | "storage" | "export" | null>(null);
  const [notice, setNotice] = useState("");
  const [context,setContext]=useState<{x:number;y:number;nodeId:string|null}|null>(null);
  const [viewer,setViewer]=useState<{asset:Asset;binding:NodeAsset}|null>(null);
  const [appearance,setAppearance]=useState<"dark"|"light"|"system">("dark");
  const [recentColors,setRecentColors]=useState<RecentColors>(EMPTY_RECENT_COLORS);
  const [clipboardCount,setClipboardCount]=useState(0);
  const [presentation,setPresentation]=useState(false);
  const history = useRef<MapDocument[]>([]); const future = useRef<MapDocument[]>([]); const saveTimer = useRef<ReturnType<typeof setTimeout>|null>(null);
  const clipboard = useRef<MindmapNode[]>([]); const importInput = useRef<HTMLInputElement>(null);
  const imageInput=useRef<HTMLInputElement>(null);const freeImageInput=useRef<HTMLInputElement>(null);const imageTarget=useRef<string|null>(null);
  const active = documents.find(d => d.mindmap.id === activeId) ?? null;

  useEffect(() => { (async () => { await localDatabase.init();const preferences=await localDatabase.settings();setAppearance(preferences.appearance);setRecentColors(preferences.recentColors); let docs = (await localDatabase.list()).map(normalize); if (!docs.length) { const welcome=createWelcomeDocument(); docs=[welcome]; await localDatabase.save(welcome); } setDocuments(docs); setReady(true); navigator.storage?.persist?.(); if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(()=>undefined); })(); }, []);
  useEffect(()=>{document.documentElement.classList.remove("appearance-dark","appearance-light","appearance-system");document.documentElement.classList.add(`appearance-${appearance}`)},[appearance]);
  useEffect(()=>{if(ready)void localDatabase.saveSettings({recentColors})},[ready,recentColors]);
  const flash = (message: string) => { setNotice(message); setTimeout(()=>setNotice(""),2200); };

  const replace = useCallback((doc: MapDocument, record = true) => {
    if (record && active) { history.current.push(structuredClone(active)); history.current = history.current.slice(-80); future.current=[]; }
    setDocuments(ds => ds.map(d => d.mindmap.id === doc.mindmap.id ? doc : d)); setSaved(false);
    if (saveTimer.current) clearTimeout(saveTimer.current);
    saveTimer.current=setTimeout(async()=>{ await localDatabase.save(doc); setSaved(true); },450);
  }, [active]);

  const create = () => { const doc=createMapDocument(); setDocuments(ds=>[doc,...ds]); localDatabase.save(doc); setActiveId(doc.mindmap.id); setSelected([doc.nodes[0].id]); history.current=[]; };
  const add = useCallback((kind: "child"|"sibling", referenceId?: string) => { if (!active) return; const current=active.nodes.find(n=>n.id===(referenceId??selected[0])) ?? active.nodes[0]; const parentId=kind==="child"?current.id:current.parentId; const siblings=active.nodes.filter(n=>n.parentId===parentId); const node=createNodeFromReference({reference:current,kind,parentId,siblingCount:siblings.length,id:id()}); replace({...active,nodes:[...active.nodes,node],mindmap:{...active.mindmap,updatedAt:Date.now()}}); setSelected([node.id]); setEditingId(node.id); },[active,selected,replace]);
  const recordColor=useCallback((role:ColorRole,color:string)=>setRecentColors(current=>registerRecentColor(current,role,color)),[]);
  const removeSelected = useCallback((targetIds: string[] = selected) => { if (!active||!targetIds.length) return; const root=active.nodes.find(n=>!n.parentId); if(targetIds.includes(root?.id??""))return; const doomed=new Set(targetIds); let changed=true; while(changed){changed=false; active.nodes.forEach(n=>{if(n.parentId&&doomed.has(n.parentId)&&!doomed.has(n.id)){doomed.add(n.id);changed=true;}})} const remainingBindings=active.nodeAssets.filter(binding=>!doomed.has(binding.nodeId));const usedAssets=new Set(remainingBindings.map(binding=>binding.assetId));active.assets.filter(asset=>!usedAssets.has(asset.id)).forEach(asset=>void assetStore.remove(asset));replace({...active,nodes:active.nodes.filter(n=>!doomed.has(n.id)),connections:active.connections.filter(c=>!doomed.has(c.sourceId)&&!doomed.has(c.targetId)),nodeAssets:remainingBindings,assets:active.assets.filter(asset=>usedAssets.has(asset.id))}); setSelected([]); },[active,selected,replace]);
  const undo=useCallback(()=>{if(!active||!history.current.length)return; const prev=history.current.pop()!; future.current.push(active); setDocuments(ds=>ds.map(d=>d.mindmap.id===prev.mindmap.id?prev:d)); localDatabase.save(prev);},[active]);
  const redo=useCallback(()=>{if(!active||!future.current.length)return; const next=future.current.pop()!; history.current.push(active);setDocuments(ds=>ds.map(d=>d.mindmap.id===next.mindmap.id?next:d));localDatabase.save(next);},[active]);

  const duplicate = useCallback((targetIds: string[] = selected) => { if(!active||!targetIds.length)return; const chosen=active.nodes.filter(n=>targetIds.includes(n.id)); const remap=new Map(chosen.map(n=>[n.id,id()])); const copies=chosen.map(n=>({...n,id:remap.get(n.id)!,parentId:n.parentId&&remap.has(n.parentId)?remap.get(n.parentId)!:n.parentId,text:`${n.text} copy`,x:n.x+36,y:n.y+36,createdAt:Date.now(),updatedAt:Date.now()})); replace({...active,nodes:[...active.nodes,...copies]});setSelected(copies.map(n=>n.id)); },[active,selected,replace]);
  const copy = useCallback((targetIds: string[] = selected)=>{if(active){clipboard.current=active.nodes.filter(n=>targetIds.includes(n.id)).map(n=>structuredClone(n));setClipboardCount(clipboard.current.length)}},[active,selected]);
  const pasteNodes = useCallback(()=>{if(!active||!clipboard.current.length)return;const remap=new Map(clipboard.current.map(n=>[n.id,id()]));const copies=clipboard.current.map(n=>({...n,id:remap.get(n.id)!,mindmapId:active.mindmap.id,parentId:n.parentId&&remap.has(n.parentId)?remap.get(n.parentId)!:n.parentId,x:n.x+52,y:n.y+52,createdAt:Date.now(),updatedAt:Date.now()}));replace({...active,nodes:[...active.nodes,...copies]});setSelected(copies.map(n=>n.id));},[active,replace]);
  const outdent=useCallback(()=>{if(!active||selected.length!==1)return;const node=active.nodes.find(n=>n.id===selected[0]);const parent=active.nodes.find(n=>n.id===node?.parentId);if(!node||!parent)return;replace({...active,nodes:active.nodes.map(n=>n.id===node.id?{...n,parentId:parent.parentId,x:n.x-180,updatedAt:Date.now()}:n)});},[active,selected,replace]);
  const connect=useCallback(()=>{if(!active||selected.length!==2)return;const exists=active.connections.some(c=>c.sourceId===selected[0]&&c.targetId===selected[1]);if(exists)return;const now=Date.now();replace({...active,connections:[...active.connections,{id:id(),mindmapId:active.mindmap.id,sourceId:selected[0],targetId:selected[1],label:"",color:"#d183ff",style:"straight",createdAt:now,updatedAt:now}]});flash("Connection created");},[active,selected,replace]);
  const addImage=useCallback(async(nodeId:string,file:File)=>{if(!active)return;try{const asset=await assetStore.write(file,active.mindmap.id,active.assets);const now=Date.now(),width=170,height=Math.round(width/(asset.width&&asset.height?asset.width/asset.height:16/9));replace({...active,assets:active.assets.some(a=>a.id===asset.id)?active.assets:[...active.assets,asset],nodeAssets:[...active.nodeAssets,{id:id(),nodeId,assetId:asset.id,position:"top",width,height,objectFit:"cover",caption:"",createdAt:now}]});flash("Image stored offline");}catch(error){flash(error instanceof Error?error.message:"Could not add image");}},[active,replace]);
  const addImageUrl=useCallback(async(nodeId:string,url:string)=>{try{const response=await fetch(url);if(!response.ok)throw new Error("Image download failed");const blob=await response.blob();if(!blob.type.startsWith("image/"))throw new Error("URL does not point to an image");const name=new URL(url).pathname.split("/").pop()||"remote-image";await addImage(nodeId,new File([blob],name,{type:blob.type}));}catch(error){flash(error instanceof Error?`${error.message}. The source may block browser downloads.`:"Could not import URL")}},[addImage]);
  const addCanvasImage=useCallback(async(file:File,x:number,y:number)=>{if(!active)return;try{const asset=await assetStore.write(file,active.mindmap.id,active.assets);const now=Date.now(),nodeId=id(),ratio=asset.width&&asset.height?asset.width/asset.height:1.4,width=220,height=Math.round(220/ratio);const node:MindmapNode={id:nodeId,mindmapId:active.mindmap.id,parentId:null,text:"",richText:"",elementKind:"image",description:"",notes:"",x,y,width,height,background:"transparent",color:"#f8f8fb",borderColor:"transparent",emoji:"",collapsed:false,sortOrder:active.nodes.length+1,createdAt:now,updatedAt:now};replace({...active,nodes:[...active.nodes,node],assets:active.assets.some(a=>a.id===asset.id)?active.assets:[...active.assets,asset],nodeAssets:[...active.nodeAssets,{id:id(),nodeId,assetId:asset.id,position:"top",width,height,objectFit:"cover",caption:"",createdAt:now}]});setSelected([nodeId]);flash("Free image added")}catch(error){flash(error instanceof Error?error.message:"Could not add image")}},[active,replace]);
  const removeImage=useCallback(async(binding:MapDocument["nodeAssets"][number])=>{if(!active)return;const remaining=active.nodeAssets.filter(item=>item.id!==binding.id);const stillUsed=remaining.some(item=>item.assetId===binding.assetId);const asset=active.assets.find(item=>item.id===binding.assetId);replace({...active,nodeAssets:remaining,assets:stillUsed?active.assets:active.assets.filter(item=>item.id!==binding.assetId)});if(asset&&!stillUsed)await assetStore.remove(asset);},[active,replace]);
  const updateNodeAsset=useCallback((binding:MapDocument["nodeAssets"][number])=>{if(active)replace({...active,nodeAssets:active.nodeAssets.map(item=>item.id===binding.id?binding:item),nodes:active.nodes.map(node=>node.id===binding.nodeId&&node.elementKind==="image"?{...node,width:binding.width,height:binding.height,updatedAt:Date.now()}:node)});},[active,replace]);
  const reparent=useCallback((nodeId:string,parentId:string)=>{if(!active||nodeId===parentId)return;const descendants=new Set([nodeId]);let changed=true;while(changed){changed=false;active.nodes.forEach(n=>{if(n.parentId&&descendants.has(n.parentId)&&!descendants.has(n.id)){descendants.add(n.id);changed=true}})}if(descendants.has(parentId)){flash("A branch cannot be moved into itself");return;}const siblings=active.nodes.filter(n=>n.parentId===parentId);replace({...active,nodes:active.nodes.map(n=>n.id===nodeId?{...n,parentId,sortOrder:siblings.length+1,updatedAt:Date.now()}:n)});flash("Branch moved");},[active,replace]);
  const updateConnection=useCallback((connection:MapDocument["connections"][number])=>{if(active)replace({...active,connections:active.connections.map(item=>item.id===connection.id?connection:item)});},[active,replace]);
  const deleteConnection=useCallback((connectionId:string)=>{if(active)replace({...active,connections:active.connections.filter(item=>item.id!==connectionId)});},[active,replace]);

  useEffect(()=>{ const key=(e:KeyboardEvent)=>{
    if(!active)return;
    if(presentation){if(e.key==="Escape")setPresentation(false);return;}
    const target=e.target as HTMLElement|null;
    if(editingId||target?.isContentEditable||target?.matches("input, textarea, select"))return;
    const mod=e.ctrlKey||e.metaKey;
    if(e.key==="Tab"){e.preventDefault();if(e.shiftKey)outdent();else add("child");}
    else if(e.key==="Enter"){e.preventDefault();add("sibling");}
    else if(e.key==="Delete"||e.key==="Backspace")removeSelected();
    else if(mod&&e.key.toLowerCase()==="z"){e.preventDefault();if(e.shiftKey)redo();else undo();}
    else if(mod&&e.key.toLowerCase()==="k"){e.preventDefault();setOverlay("commands");}
    else if(mod&&e.key.toLowerCase()==="f"){e.preventDefault();setOverlay("search");}
    else if(mod&&e.key.toLowerCase()==="d"){e.preventDefault();duplicate();}
    else if(mod&&e.key.toLowerCase()==="c")copy();
    else if(mod&&e.key.toLowerCase()==="v"&&clipboard.current.length){e.preventDefault();pasteNodes();}
    else if(mod&&e.key.toLowerCase()==="a"){e.preventDefault();setSelected(active.nodes.map(n=>n.id));}
    else if(e.key==="F2"&&selected[0])setEditingId(selected[0]);
    else if(e.key==="Escape"){setSelected([]);setOverlay(null);}
    else if(e.key==="+")setZoom(z=>Math.min(4,z+.1));
    else if(e.key==="-")setZoom(z=>Math.max(.35,z-.1));
    else if(e.key==="0"){setZoom(1);setPan({x:innerWidth*.43,y:innerHeight*.45});}
    else if(e.key.startsWith("Arrow")&&selected[0]){const current=active.nodes.find(n=>n.id===selected[0]);if(!current)return;const candidates=active.nodes.filter(n=>n.id!==current.id).filter(n=>e.key==="ArrowRight"?n.x>current.x:e.key==="ArrowLeft"?n.x<current.x:e.key==="ArrowDown"?n.y>current.y:n.y<current.y);candidates.sort((a,b)=>Math.hypot(a.x-current.x,a.y-current.y)-Math.hypot(b.x-current.x,b.y-current.y));if(candidates[0])setSelected([candidates[0].id]);}
  };addEventListener("keydown",key);return()=>removeEventListener("keydown",key);},[active,editingId,presentation,selected,add,outdent,removeSelected,undo,redo,duplicate,copy,pasteNodes]);
  useEffect(()=>{const paste=(e:ClipboardEvent)=>{if(!active||editingId||presentation)return;const file=[...(e.clipboardData?.files??[])].find(item=>item.type.startsWith("image/"));if(file){e.preventDefault();const target=selected[0]??active.nodes.find(n=>!n.parentId)?.id;if(target)addImage(target,file);}};addEventListener("paste",paste);return()=>removeEventListener("paste",paste);},[active,editingId,presentation,selected,addImage]);

  const exportDoc=()=>{if(!active)return;const blob=new Blob([JSON.stringify(active,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`${active.mindmap.title.replace(/\W+/g,"-").toLowerCase()}.mindmap.json`;a.click();URL.revokeObjectURL(a.href);};
  const exportMarkdown=()=>{if(!active)return;const children=new Map<string|null,MindmapNode[]>();active.nodes.forEach(n=>children.set(n.parentId,[...(children.get(n.parentId)??[]),n]));const root=active.nodes.find(n=>!n.parentId);if(!root)return;const lines=[`# ${root.text}`];const walk=(parent:string,depth:number)=>{(children.get(parent)??[]).sort((a,b)=>a.sortOrder-b.sortOrder).forEach(n=>{lines.push(`${"  ".repeat(Math.max(0,depth-2))}${depth===2?"## ":"- "}${n.text.replace(/\n/g," ")}`);walk(n.id,depth+1)})};walk(root.id,2);download(`${active.mindmap.title}.md`,lines.join("\n\n"),"text/markdown");};
  const exportBackup=()=>download(`luma-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({version:1,exportedAt:Date.now(),documents},null,2),"application/json");
  const importDoc=async(file:File)=>{try{let packaged:MapDocument|null=null;if(file.name.toLowerCase().endsWith(".mindmap"))packaged=normalize(await importPortable(file));const text=packaged?"":await file.text();if(file.name.toLowerCase().endsWith(".md")){const imported=parseMarkdown(text);setDocuments(ds=>[imported,...ds]);await localDatabase.save(imported);setActiveId(imported.mindmap.id);flash("Markdown imported");return;}const value=packaged??JSON.parse(text) as Partial<MapDocument>&{documents?:MapDocument[]};if("documents" in value&&Array.isArray(value.documents)){const restored=value.documents.map(normalize);for(const doc of restored)await localDatabase.save(doc);setDocuments(ds=>[...restored,...ds.filter(d=>!restored.some(r=>r.mindmap.id===d.mindmap.id))]);flash(`${restored.length} maps restored`);return;}if(value.version!==1||!value.mindmap||!Array.isArray(value.nodes))throw new Error("Unsupported mind map file");const original=normalize(value as MapDocument);const mapId=id();const remap=new Map(original.nodes.map(n=>[n.id,id()]));const assetMap=new Map(original.assets.map(a=>[a.id,id()]));const imported:MapDocument={...original,mindmap:{...original.mindmap,id:mapId,title:`${original.mindmap.title} (imported)`,createdAt:Date.now(),updatedAt:Date.now(),deletedAt:null},nodes:original.nodes.map(n=>({...n,id:remap.get(n.id)!,mindmapId:mapId,parentId:n.parentId?remap.get(n.parentId)??null:null})),connections:original.connections.map(c=>({...c,id:id(),mindmapId:mapId,sourceId:remap.get(c.sourceId)??c.sourceId,targetId:remap.get(c.targetId)??c.targetId})),assets:packaged?original.assets.map(a=>({...a,id:assetMap.get(a.id)!,mindmapId:mapId})):[],nodeAssets:packaged?original.nodeAssets.map(b=>({...b,id:id(),nodeId:remap.get(b.nodeId)??b.nodeId,assetId:assetMap.get(b.assetId)??b.assetId})):[]};setDocuments(ds=>[imported,...ds]);await localDatabase.save(imported);setActiveId(mapId);flash("Mind map imported");}catch(error){flash(error instanceof Error?error.message:"Invalid file");}};
  const runLayout=()=>{if(active)replace({...active,nodes:autoLayout(active.nodes,active.mindmap.layout)});setOverlay(null)};
  const addAt=(clientX:number,clientY:number)=>{if(!active)return;const now=Date.now();const node:MindmapNode={id:id(),mindmapId:active.mindmap.id,parentId:null,text:"New idea",description:"",notes:"",x:(clientX-pan.x-62)/zoom,y:(clientY-pan.y-52)/zoom,width:170,height:58,background:"#222936",color:"#f8f8fb",borderColor:"#41495a",emoji:"",collapsed:false,sortOrder:active.nodes.length+1,createdAt:now,updatedAt:now};replace({...active,nodes:[...active.nodes,node]});setSelected([node.id]);setEditingId(node.id)};
  const addFreeText=()=>{if(!active)return;const now=Date.now();const node:MindmapNode={id:id(),mindmapId:active.mindmap.id,parentId:null,text:"",richText:"Double-click or use the inspector to write",elementKind:"text",description:"",notes:"",x:(innerWidth*.5-pan.x)/zoom,y:(innerHeight*.45-pan.y)/zoom,width:230,height:70,background:"transparent",color:"#f8f8fb",borderColor:"transparent",emoji:"",collapsed:false,sortOrder:active.nodes.length+1,createdAt:now,updatedAt:now};replace({...active,nodes:[...active.nodes,node]});setSelected([node.id])};
  const trashActive=()=>{if(!active)return;replace({...active,mindmap:{...active.mindmap,deletedAt:Date.now(),updatedAt:Date.now()}});setActiveId(null);setOverlay(null)};
  const toggleTheme=()=>{const next=appearance==="dark"?"light":appearance==="light"?"system":"dark";setAppearance(next);void localDatabase.saveSettings({appearance:next});setOverlay(null);flash(`Appearance: ${next}`)};
  const cleanAssets=async()=>{const used=new Set(documents.flatMap(doc=>doc.assets.map(asset=>asset.storagePath)));const count=await assetStore.cleanUnused(used);flash(`${count} unused asset${count===1?"":"s"} removed`)};
  const deleteAll=async()=>{if(!confirm("Delete every local map and image? This cannot be undone."))return;for(const doc of documents)for(const asset of doc.assets)await assetStore.remove(asset);await localDatabase.clear();setDocuments([]);setActiveId(null);setOverlay(null);flash("All local data deleted")};

  if(!ready)return <div className="boot"><span className="brand-mark">L</span><p>Opening your local workspace…</p></div>;
  return <>
    <input ref={importInput} hidden type="file" accept=".json,.mindmap.json,.mindmap,.md,application/json,text/markdown" onChange={e=>{const file=e.target.files?.[0];if(file)importDoc(file);e.currentTarget.value=""}}/>
    <input ref={imageInput} hidden type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{const file=e.target.files?.[0],target=imageTarget.current;if(file&&target)addImage(target,file);e.currentTarget.value=""}}/>
    <input ref={freeImageInput} hidden type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{const file=e.target.files?.[0];if(file)addCanvasImage(file,(innerWidth*.5-pan.x)/zoom,(innerHeight*.45-pan.y)/zoom);e.currentTarget.value=""}}/>
    {active ? <Editor doc={active} selected={selected} editingId={editingId} zoom={zoom} pan={pan} saved={saved} sidebar presentation={presentation} recentColors={recentColors} onColorUsed={recordColor} onPresentation={setPresentation} onBack={()=>{setPresentation(false);setActiveId(null);setSelected([])}} onDoc={replace} onSelect={ids=>{setSelected(ids);setContext(null)}} onEdit={setEditingId} onAdd={add} onDelete={removeSelected} onUndo={undo} onRedo={redo} onExport={()=>setOverlay("export")} onShortcuts={()=>setOverlay("shortcuts")} onCommand={()=>setOverlay("commands")} onSearch={()=>setOverlay("search")} onZoom={setZoom} onPan={setPan} onImage={addImage} onImageUrl={addImageUrl} onCanvasImage={addCanvasImage} onAddFreeText={addFreeText} onAddFreeImage={()=>freeImageInput.current?.click()} onConnect={connect} onRemoveImage={removeImage} onNodeAsset={updateNodeAsset} onReparent={reparent} onContext={setContext} onOpenImage={(asset,binding)=>setViewer({asset,binding})} onConnection={updateConnection} onDeleteConnection={deleteConnection}/>
    : <Dashboard documents={documents} onOpen={d=>{setActiveId(d.mindmap.id);setSelected([d.nodes.find(n=>!n.parentId)?.id??""]);history.current=[]}} onCreate={create} onToggleFavorite={d=>replace({...d,mindmap:{...d.mindmap,favorite:!d.mindmap.favorite}})} onTrash={d=>replace({...d,mindmap:{...d.mindmap,deletedAt:Date.now()}})} onRestore={d=>replace({...d,mindmap:{...d.mindmap,deletedAt:null}})} onDeletePermanent={async d=>{setDocuments(ds=>ds.filter(item=>item.mindmap.id!==d.mindmap.id));await localDatabase.remove(d.mindmap.id);for(const asset of d.assets)await assetStore.remove(asset);flash("Map permanently deleted")}} onImport={()=>importInput.current?.click()} onBackup={exportBackup}/>} 
    {overlay && <div className="overlay"><button className="overlay-dismiss" aria-label="Close dialog" onClick={()=>setOverlay(null)}/><div className={`modal ${overlay}`} role="dialog" aria-modal="true">{overlay==="commands"?<CommandPalette onClose={()=>setOverlay(null)} onAdd={()=>{add("child");setOverlay(null)}} onSearch={()=>setOverlay("search")} onLayout={runLayout} onExport={()=>setOverlay("export")} onMarkdown={exportMarkdown} onImport={()=>importInput.current?.click()} onConnect={()=>{connect();setOverlay(null)}} onSettings={()=>setOverlay("storage")} onTheme={toggleTheme} onTrash={trashActive}/>:overlay==="search"?<GlobalSearch documents={documents} onOpen={(doc,nodeId)=>{setActiveId(doc.mindmap.id);setSelected([nodeId]);setOverlay(null)}} onClose={()=>setOverlay(null)}/>:overlay==="storage"?<StorageSettings onClose={()=>setOverlay(null)} onBackup={exportBackup} onClean={cleanAssets} onDeleteAll={deleteAll}/>:overlay==="export"&&active?<ExportMenu doc={active} onJson={exportDoc} onMarkdown={exportMarkdown} onClose={()=>setOverlay(null)}/>:<Shortcuts onClose={()=>setOverlay(null)}/>}</div></div>}
    {context&&active&&<div className="context-menu" role="menu" tabIndex={-1} style={{left:Math.min(context.x,innerWidth-190),top:Math.min(context.y,innerHeight-310)}} onMouseLeave={()=>setContext(null)}>{context.nodeId?<><button onClick={()=>{add("child",context.nodeId??undefined);setContext(null)}}>Add child <kbd>Tab</kbd></button><button onClick={()=>{add("sibling",context.nodeId??undefined);setContext(null)}}>Add sibling <kbd>Enter</kbd></button><span/><button onClick={()=>{duplicate([context.nodeId!]);setContext(null)}}>Duplicate <kbd>⌘D</kbd></button><button onClick={()=>{copy([context.nodeId!]);setContext(null)}}>Copy <kbd>⌘C</kbd></button><button onClick={()=>{imageTarget.current=context.nodeId;imageInput.current?.click();setContext(null)}}>Add image</button><button onClick={()=>{const node=active.nodes.find(n=>n.id===context.nodeId);if(node)replace({...active,nodes:active.nodes.map(n=>n.id===node.id?{...n,collapsed:!n.collapsed}:n)});setContext(null)}}>Collapse / expand</button><span/><button className="danger" onClick={()=>{removeSelected([context.nodeId!]);setContext(null)}}>Delete <kbd>Del</kbd></button></>:<><button onClick={()=>{addAt(context.x,context.y);setContext(null)}}>Add node</button><button onClick={()=>{pasteNodes();setContext(null)}} disabled={!clipboardCount}>Paste <kbd>⌘V</kbd></button><button onClick={()=>{setSelected(active.nodes.map(n=>n.id));setContext(null)}}>Select all <kbd>⌘A</kbd></button><span/><button onClick={()=>{setZoom(1);setPan({x:innerWidth*.43,y:innerHeight*.45});setContext(null)}}>Fit view <kbd>0</kbd></button><button onClick={()=>{runLayout();setContext(null)}}>Auto layout</button></>}</div>}
    {viewer&&<ImageViewer asset={viewer.asset} onClose={()=>setViewer(null)}/>} 
    {notice&&<div className="toast">{notice}</div>}
  </>;
}

function CommandPalette({onClose,onAdd,onSearch,onLayout,onExport,onMarkdown,onImport,onConnect,onSettings,onTheme,onTrash}:{onClose:()=>void;onAdd:()=>void;onSearch:()=>void;onLayout:()=>void;onExport:()=>void;onMarkdown:()=>void;onImport:()=>void;onConnect:()=>void;onSettings:()=>void;onTheme:()=>void;onTrash:()=>void}){const[query,setQuery]=useState("");const inputRef=useRef<HTMLInputElement>(null);useEffect(()=>inputRef.current?.focus(),[]);const actions=[{icon:<FilePlus2/>,name:"Create child node",hint:"Tab",run:onAdd},{icon:<Search/>,name:"Search maps and nodes",hint:"⌘ F",run:onSearch},{icon:<Link2/>,name:"Connect selected nodes",hint:"",run:onConnect},{icon:<LayoutPanelLeft/>,name:"Apply automatic layout",hint:"",run:onLayout},{icon:<Download/>,name:"Export mind map",hint:"",run:onExport},{icon:<Download/>,name:"Export as Markdown",hint:"",run:onMarkdown},{icon:<Upload/>,name:"Import JSON or Markdown",hint:"",run:onImport},{icon:<Settings/>,name:"Storage settings",hint:"",run:onSettings},{icon:<Moon/>,name:"Toggle appearance",hint:"",run:onTheme},{icon:<Trash2/>,name:"Move map to trash",hint:"",run:onTrash}].filter(action=>action.name.toLowerCase().includes(query.toLowerCase()));return <><div className="command-search"><Command/><input ref={inputRef} value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")actions[0]?.run();if(e.key==="Escape")onClose()}} placeholder="Type a command or search…"/><kbd>ESC</kbd></div><p className="command-group">{actions.length?"ACTIONS":"NO MATCHES"}</p>{actions.map((a,i)=><button key={a.name} className={i===0?"active":""} onClick={a.run}>{a.icon}<span>{a.name}</span><kbd>{a.hint}</kbd></button>)}</>}
function Shortcuts({onClose}:{onClose:()=>void}){const rows=[["Tab","Add child"],["Enter","Add sibling"],["Shift + Enter","Line break while editing"],["Shift + Tab","Outdent"],["Delete","Delete node"],["⌘ Z","Undo"],["⌘ ⇧ Z","Redo"],["⌘ D","Duplicate"],["⌘ C / ⌘ V","Copy / paste"],["F2","Edit title"],["⌘ K","Command palette"],["+ / −","Zoom"],["0","Fit view"],["Esc","Deselect"]];return <><header><div><p>QUICK REFERENCE</p><h2>Keyboard shortcuts</h2></div><button onClick={onClose}><X/></button></header><div className="shortcut-list">{rows.map(r=><div key={r[0]}><span>{r[1]}</span><kbd>{r[0]}</kbd></div>)}</div></>}

function GlobalSearch({documents,onOpen,onClose}:{documents:MapDocument[];onOpen:(doc:MapDocument,nodeId:string)=>void;onClose:()=>void}){const[q,setQ]=useState("");const inputRef=useRef<HTMLInputElement>(null);useEffect(()=>inputRef.current?.focus(),[]);const results=q.trim()?documents.flatMap(doc=>doc.nodes.filter(node=>`${node.text} ${node.richText?.replace(/<[^>]*>/g," ")??""}`.toLowerCase().includes(q.toLowerCase())).map(node=>({doc,node}))).slice(0,30):[];return <><div className="command-search"><Search/><input ref={inputRef} value={q} onChange={e=>setQ(e.target.value)} placeholder="Search titles and rich text…"/><button onClick={onClose}><X/></button></div><div className="search-results">{results.length?results.map(({doc,node})=><button key={node.id} onClick={()=>onOpen(doc,node.id)}><span>{node.text||node.richText?.replace(/<[^>]*>/g," ").slice(0,60)||"Image"}</span><small>{doc.mindmap.title} › {node.elementKind==="node"?(node.parentId?"Branch":"Root"):node.elementKind}</small></button>):<p>{q?"No matching ideas":"Start typing to search every local map"}</p>}</div></>}

function StorageSettings({onClose,onBackup,onClean,onDeleteAll}:{onClose:()=>void;onBackup:()=>void;onClean:()=>void;onDeleteAll:()=>void}){const[stats,setStats]=useState<{maps:number;nodes:number;bytes:number;mode:string}|null>(null);const[working,setWorking]=useState(false);const[persistent,setPersistent]=useState<boolean|null>(null);useEffect(()=>{localDatabase.stats().then(setStats);navigator.storage?.persisted?.().then(setPersistent)},[]);const exportDb=async()=>{const bytes=await localDatabase.exportDatabase();const blob=new Blob([bytes as Uint8Array<ArrayBuffer>],{type:"application/vnd.sqlite3"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="luma-mindmaps.sqlite3";a.click();URL.revokeObjectURL(a.href)};return <><header className="settings-head"><div><p>LOCAL-FIRST STORAGE</p><h2>Storage & backup</h2></div><button onClick={onClose}><X/></button></header><div className="storage-body"><div className="storage-banner"><HardDrive/><div><strong>Your maps are stored locally on this device.</strong><span>{stats?.mode==="sqlite-opfs"?"SQLite + persistent OPFS":"SQLite memory fallback"} · Persistence {persistent?"granted":"not guaranteed"}</span></div></div><div className="storage-stats"><div><strong>{stats?.maps??"—"}</strong><span>Maps</span></div><div><strong>{stats?.nodes??"—"}</strong><span>Nodes</span></div><div><strong>{stats?formatBytes(stats.bytes):"—"}</strong><span>Database</span></div></div><div className="storage-actions"><button onClick={onBackup}><Download/>Export backup</button><button onClick={exportDb}><Database/>Export database</button><button onClick={onClean}><HardDrive/>Clean unused assets</button><button onClick={async()=>{setWorking(true);await localDatabase.optimize();setStats(await localDatabase.stats());setWorking(false)}}><HardDrive/>{working?"Optimizing…":"Optimize database"}</button><button className="storage-danger" onClick={onDeleteAll}><Trash2/>Delete all local data</button></div></div></>}

function ExportMenu({doc,onJson,onMarkdown,onClose}:{doc:MapDocument;onJson:()=>void;onMarkdown:()=>void;onClose:()=>void}){const[working,setWorking]=useState("");const run=async(label:string,task:()=>Promise<void>|void)=>{setWorking(label);try{await task()}finally{setWorking("")}};const formats=[{name:"Portable map",detail:"Includes every locally stored image",run:()=>exportPortable(doc),ext:".mindmap"},{name:"PNG image",detail:"High-resolution raster image",run:()=>exportVisual(doc,"png"),ext:".png"},{name:"SVG vector",detail:"Scalable vector with embedded assets",run:()=>exportVisual(doc,"svg"),ext:".svg"},{name:"PDF document",detail:"Canvas-sized PDF for sharing",run:()=>exportVisual(doc,"pdf"),ext:".pdf"},{name:"JSON data",detail:"Complete structured map data",run:onJson,ext:".json"},{name:"Markdown outline",detail:"Portable text hierarchy",run:onMarkdown,ext:".md"}];return <><header className="settings-head"><div><p>EXPORT MAP</p><h2>Choose a format</h2></div><button onClick={onClose}><X/></button></header><div className="export-grid">{formats.map(format=><button key={format.name} onClick={()=>run(format.name,format.run)} disabled={Boolean(working)}><span className="export-ext">{format.ext}</span><strong>{working===format.name?"Preparing…":format.name}</strong><small>{format.detail}</small></button>)}</div></>}

function ImageViewer({asset,onClose}:{asset:Asset;onClose:()=>void}){const[src,setSrc]=useState("");const[zoom,setZoom]=useState(1);useEffect(()=>{let current="";assetStore.url(asset).then(url=>{current=url;setSrc(url)});return()=>{if(current)URL.revokeObjectURL(current)}},[asset]);return <div className="image-viewer"><header><span>{asset.fileName}</span><button onClick={onClose}><X/></button></header><div className="viewer-stage">{src&&<img src={src} alt={asset.fileName} style={{transform:`scale(${zoom})`}}/>}</div><footer><button onClick={()=>setZoom(value=>Math.max(.25,value-.25))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(value=>Math.min(4,value+.25))}>+</button><button onClick={()=>setZoom(1)}>Fit screen</button><a href={src} download={asset.fileName}>Download</a></footer></div>}

function download(name:string,content:string,type:string){const blob=new Blob([content],{type});const anchor=document.createElement("a");anchor.href=URL.createObjectURL(blob);anchor.download=name;anchor.click();URL.revokeObjectURL(anchor.href)}
function formatBytes(bytes:number){if(!bytes)return"0 KB";const units=["B","KB","MB","GB"];const index=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),3);return`${(bytes/1024**index).toFixed(index?1:0)} ${units[index]}`}

function parseMarkdown(markdown:string):MapDocument{const lines=markdown.split(/\r?\n/).filter(line=>line.trim());const title=lines.find(line=>/^#\s/.test(line))?.replace(/^#\s+/,"")||"Imported Markdown";const doc=createMapDocument(title);let parent=doc.nodes[0];let lastHeading=parent;let order=1;for(const line of lines){if(/^#\s/.test(line))continue;const heading=line.match(/^##+\s+(.+)/);const bullet=line.match(/^\s*[-*+]\s+(.+)/);if(!heading&&!bullet)continue;const text=(heading?.[1]??bullet?.[1]??"").trim();const node:MindmapNode={...parent,id:id(),mindmapId:doc.mindmap.id,parentId:heading?doc.nodes[0].id:lastHeading.id,text,emoji:"",description:"",notes:"",x:heading?280:560,y:order*80-160,background:heading?"#284b63":"#222936",borderColor:heading?"#3e7397":"#41495a",sortOrder:order++,createdAt:Date.now(),updatedAt:Date.now()};doc.nodes.push(node);if(heading)lastHeading=node;parent=node;}return doc}
