"use client";
import { useMemo, useState } from "react";
import { AlignCenter, AlignLeft, AlignRight, ArrowLeft, Bold, Check, ChevronDown, CircleHelp, Command, Focus, Grid3X3, ImagePlus, Italic, LayoutPanelLeft, Link2, List, ListOrdered, Maximize, Menu, MousePointer2, PanelRightClose, Pilcrow, Plus, Redo2, Search, Share2, Sparkles, Star, Type, Underline, Undo2, ZoomIn, ZoomOut } from "lucide-react";
import { MindCanvas } from "./MindCanvas";
import type { Asset, LayoutName, MapDocument, NodeAsset, NodeConnection, NodeIconName, ThemeName } from "@/src/types/domain";
import { autoLayout } from "@/src/lib/layout";
import { NODE_ICON_OPTIONS, NodeIcon } from "./NodeIcon";

const NODE_PALETTE=["#7057ff","#24779d","#268566","#bb713c","#b84f6b","#5f6573","#20242c","#f2f3f5"];
const TEXT_PALETTE=["#ffffff","#e4e7ec","#b9c0cc","#17191e","#ffe08a","#9ee7cf","#b9dcff","#efadba"];
const CONNECTION_PALETTE=["#8b78ff","#4ba3d2","#43b88b","#e1a65a","#de7086","#a1a7b2"];

interface Props {
  doc: MapDocument; selected: string[]; editingId: string | null; zoom: number; pan: {x:number;y:number}; saved: boolean; sidebar: boolean;
  onBack: () => void; onDoc: (doc: MapDocument, history?: boolean) => void; onSelect: (ids: string[]) => void; onEdit: (id: string | null) => void;
  onAdd: (kind: "child" | "sibling") => void; onDelete: () => void; onUndo: () => void; onRedo: () => void; onExport: () => void; onShortcuts: () => void; onCommand: () => void; onSearch: () => void;
  onZoom: (zoom: number) => void; onPan: (pan: {x:number;y:number}) => void;
  onImage: (nodeId: string, file: File) => void; onConnect: () => void;
  onRemoveImage: (binding: NodeAsset) => void; onNodeAsset: (binding: NodeAsset) => void;
  onReparent: (nodeId: string, parentId: string) => void;
  onContext: (menu:{x:number;y:number;nodeId:string|null}) => void;
  onOpenImage:(asset:Asset,binding:NodeAsset)=>void;
  onConnection:(connection:NodeConnection)=>void;onDeleteConnection:(id:string)=>void;
  onImageUrl:(nodeId:string,url:string)=>void;onCanvasImage:(file:File,x:number,y:number)=>void;
  onAddFreeText:()=>void; onAddFreeImage:()=>void;
}

export function Editor(p: Props) {
  const [outline,setOutline]=useState(false);const[grid,setGrid]=useState(true);const[laser,setLaser]=useState(false);
  const selectedNode = p.doc.nodes.find(n => n.id === p.selected[0]);
  const updateNode = (id: string, patch: object, history = true) => p.onDoc({ ...p.doc, mindmap: { ...p.doc.mindmap, updatedAt: Date.now() }, nodes: p.doc.nodes.map(n => n.id === id ? { ...n, ...patch, updatedAt: Date.now() } : n) }, history);
  const setLayout = (layout: LayoutName) => p.onDoc({ ...p.doc, mindmap: { ...p.doc.mindmap, layout, updatedAt: Date.now() } });
  const selectedImages = selectedNode ? p.doc.nodeAssets.filter(binding=>binding.nodeId===selectedNode.id) : [];
  const outlineNodes=useMemo(()=>{const result:{node:MapDocument["nodes"][number];depth:number}[]=[];const walk=(parent:string|null,depth:number)=>p.doc.nodes.filter(n=>n.parentId===parent).sort((a,b)=>a.sortOrder-b.sortOrder).forEach(node=>{result.push({node,depth});if(!node.collapsed)walk(node.id,depth+1)});walk(null,0);return result},[p.doc.nodes]);
  return <main className={`editor-shell theme-${p.doc.mindmap.theme}`}>
    <header className="editor-topbar">
      <button className="icon-btn" onClick={p.onBack} aria-label="Back to dashboard"><ArrowLeft/></button><div className="editor-brand"><span className="brand-mark small">L</span></div><span className="top-divider"/>
      <input className="map-title" value={p.doc.mindmap.title} onChange={e => p.onDoc({ ...p.doc, mindmap: { ...p.doc.mindmap, title: e.target.value, updatedAt: Date.now() } }, false)} aria-label="Map title"/>
      <button className={`icon-btn star ${p.doc.mindmap.favorite ? "active" : ""}`} onClick={() => p.onDoc({...p.doc, mindmap:{...p.doc.mindmap, favorite:!p.doc.mindmap.favorite}})}><Star/></button>
      <div className="save-state"><span className={p.saved ? "saved-dot" : "saving-dot"}/>{p.saved ? "Saved locally" : "Saving…"}</div>
      <div className="top-actions"><button className="icon-btn" onClick={p.onUndo}><Undo2/></button><button className="icon-btn" onClick={p.onRedo}><Redo2/></button><button className="share-button" onClick={p.onExport}><Share2/>Export</button><button className="icon-btn" onClick={p.onCommand}><Command/></button></div>
    </header>
    <div className="editor-body">
      <aside className="editor-rail"><button className={!outline?"active":""} onClick={()=>setOutline(false)}><Sparkles/><span>Map</span></button><button className={outline?"active":""} onClick={()=>setOutline(value=>!value)}><LayoutPanelLeft/><span>Outline</span></button><button onClick={p.onSearch}><Search/><span>Search</span></button><div className="rail-spacer"/><button onClick={p.onShortcuts}><CircleHelp/><span>Help</span></button></aside>
      <section className="canvas-wrap">
        {outline&&<aside className="outline-panel"><header><span>OUTLINE</span><button onClick={()=>setOutline(false)}>×</button></header>{outlineNodes.map(({node,depth})=><button key={node.id} className={p.selected.includes(node.id)?"active":""} style={{paddingLeft:12+depth*14}} onClick={()=>p.onSelect([node.id])}><span>{node.emoji||"•"}</span>{node.text.replace(/\n/g," ")}</button>)}</aside>}
        <div className="floating-toolbar">
          <button onClick={() => p.onAdd("child")}><Plus/>Child<kbd>Tab</kbd></button><span/><label className="layout-select"><LayoutPanelLeft/><select value={p.doc.mindmap.layout} onChange={e=>{const layout=e.target.value as LayoutName;p.onDoc({...p.doc,mindmap:{...p.doc.mindmap,layout,updatedAt:Date.now()},nodes:autoLayout(p.doc.nodes,layout)})}}><option value="mindmap">Mind map</option><option value="tree-right">Tree right</option><option value="vertical">Vertical</option><option value="radial">Radial</option></select><ChevronDown/></label><button disabled={p.selected.length!==2} onClick={p.onConnect}><Link2/>Connect</button><span/><button className={grid?"active":""} onClick={()=>setGrid(value=>!value)}><Grid3X3/>Grid</button><button onClick={() => p.onPan({x: window.innerWidth/2, y: window.innerHeight/2})}><Focus/>Center</button><span/><button onClick={p.onAddFreeText}><Type/>Text</button><button onClick={p.onAddFreeImage}><ImagePlus/>Image</button><button className={laser?"active laser-active":""} onClick={()=>setLaser(value=>!value)}><MousePointer2/>Laser</button>
        </div>
        <MindCanvas nodes={p.doc.nodes} assets={p.doc.assets ?? []} nodeAssets={p.doc.nodeAssets ?? []} connections={p.doc.connections} selected={p.selected} editingId={p.editingId} zoom={p.zoom} pan={p.pan} onPan={p.onPan} onZoom={p.onZoom} onSelect={p.onSelect} grid={grid}
          onMove={(id,x,y)=>{const current=p.doc.nodes.find(n=>n.id===id);if(!current)return;const dx=x-current.x,dy=y-current.y;const descendants=new Set([id]);let changed=true;while(changed){changed=false;p.doc.nodes.forEach(n=>{if(n.parentId&&descendants.has(n.parentId)&&!descendants.has(n.id)){descendants.add(n.id);changed=true}})}p.onDoc({...p.doc,mindmap:{...p.doc.mindmap,updatedAt:Date.now()},nodes:p.doc.nodes.map(n=>descendants.has(n.id)?{...n,x:n.x+dx,y:n.y+dy,updatedAt:Date.now()}:n)},false)}} onEdit={p.onEdit} onText={(id,text)=>updateNode(id,{text},false)} onToggle={(id)=>updateNode(id,{collapsed:!p.doc.nodes.find(n=>n.id===id)?.collapsed})} onCanvasMenu={(x,y) => p.onContext({x,y,nodeId:null})} onNodeMenu={(nodeId,x,y)=>p.onContext({x,y,nodeId})} onImage={p.onImage} onReparent={p.onReparent} onOpenImage={p.onOpenImage} onCanvasImage={p.onCanvasImage} laser={laser}/>
        <div className="zoom-control"><button onClick={()=>p.onZoom(Math.max(.35,p.zoom-.1))}><ZoomOut/></button><span>{Math.round(p.zoom*100)}%</span><button onClick={()=>p.onZoom(Math.min(1.8,p.zoom+.1))}><ZoomIn/></button><button onClick={()=>{p.onZoom(1);p.onPan({x:innerWidth*.43,y:innerHeight*.45})}}><Maximize/></button></div>
        <div className="offline-pill"><span/>Offline ready</div>
      </section>
      {p.sidebar && <aside className="inspector">
        <div className="inspector-head"><div><p>INSPECTOR</p><h2>{selectedNode ? "Node" : "Map"}</h2></div><PanelRightClose/></div>
        {selectedNode ? <>
          {selectedNode.elementKind!=="image"&&<><label className="field-label">Title<input value={selectedNode.text} placeholder={selectedNode.elementKind==="text"?"Optional title":"Node title"} onChange={e=>updateNode(selectedNode.id,{text:e.target.value},false)}/></label><RichTextEditor value={selectedNode.richText??""} onChange={richText=>updateNode(selectedNode.id,{richText},false)}/></>}
          <div className="inspector-section"><h3>Colors</h3><ColorControl label="Background" value={selectedNode.background} presets={NODE_PALETTE} onChange={background=>updateNode(selectedNode.id,{background})}/><ColorControl label="Text" value={selectedNode.color} presets={TEXT_PALETTE} onChange={color=>updateNode(selectedNode.id,{color})}/><ColorControl label="Border" value={selectedNode.borderColor} presets={NODE_PALETTE} onChange={borderColor=>updateNode(selectedNode.id,{borderColor})}/>{selectedNode.parentId&&<ColorControl label="Branch connection" value={selectedNode.branchColor??"#45576a"} presets={CONNECTION_PALETTE} onChange={branchColor=>updateNode(selectedNode.id,{branchColor})}/>}</div>
          <div className="inspector-section"><h3>Typography</h3><div className="type-row"><select aria-label="Font family" value={selectedNode.fontFamily??"sans"} onChange={e=>updateNode(selectedNode.id,{fontFamily:e.target.value})}><option value="sans">Sans</option><option value="serif">Serif</option><option value="mono">Mono</option></select><select aria-label="Font size" value={selectedNode.fontSize??12} onChange={e=>updateNode(selectedNode.id,{fontSize:Number(e.target.value)})}>{[10,11,12,13,14,16,18,20,24,28,32].map(size=><option value={size} key={size}>{size}px</option>)}</select></div><div className="format-buttons"><button className={(selectedNode.fontWeight??590)>=700?"active":""} onClick={()=>updateNode(selectedNode.id,{fontWeight:(selectedNode.fontWeight??590)>=700?590:700})} aria-label="Bold"><Bold/></button><button className={selectedNode.fontStyle==="italic"?"active":""} onClick={()=>updateNode(selectedNode.id,{fontStyle:selectedNode.fontStyle==="italic"?"normal":"italic"})} aria-label="Italic"><Italic/></button><button className={selectedNode.textDecoration==="underline"?"active":""} onClick={()=>updateNode(selectedNode.id,{textDecoration:selectedNode.textDecoration==="underline"?"none":"underline"})} aria-label="Underline"><Underline/></button><span/><button className={(selectedNode.textAlign??"left")==="left"?"active":""} onClick={()=>updateNode(selectedNode.id,{textAlign:"left"})} aria-label="Align left"><AlignLeft/></button><button className={selectedNode.textAlign==="center"?"active":""} onClick={()=>updateNode(selectedNode.id,{textAlign:"center"})} aria-label="Align center"><AlignCenter/></button><button className={selectedNode.textAlign==="right"?"active":""} onClick={()=>updateNode(selectedNode.id,{textAlign:"right"})} aria-label="Align right"><AlignRight/></button></div></div>
          <div className="inspector-section"><h3>Icon & emoji</h3><div className="icon-grid"><button className={!selectedNode.icon?"active":""} onClick={()=>updateNode(selectedNode.id,{icon:null})} aria-label="No icon">None</button>{NODE_ICON_OPTIONS.map(({name,label})=><button key={name} className={selectedNode.icon===name?"active":""} onClick={()=>updateNode(selectedNode.id,{icon:name as NodeIconName})} title={label} aria-label={label}><NodeIcon name={name}/></button>)}</div><div className="emoji-editor"><input value={selectedNode.emoji} onChange={e=>updateNode(selectedNode.id,{emoji:e.target.value},false)} placeholder="Paste an emoji" aria-label="Node emoji"/><button onClick={()=>updateNode(selectedNode.id,{emoji:""})}>Remove emoji</button></div></div>
          <div className="inspector-section"><h3>Images</h3><div className="image-add-row"><label className="upload-image"><ImagePlus/>Add image<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{const file=e.target.files?.[0];if(file)p.onImage(selectedNode.id,file);e.currentTarget.value=""}}/></label><button onClick={()=>{const url=prompt("Image URL");if(url)p.onImageUrl(selectedNode.id,url)}}>From URL</button></div><small className="field-help">Size remains proportional. Images fill textless nodes and have an inner margin when combined with text.</small>{selectedImages.map(binding=>{const asset=p.doc.assets.find(a=>a.id===binding.assetId);const ratio=(asset?.width&&asset?.height)?asset.width/asset.height:binding.width/binding.height;return <div className="image-setting-card" key={binding.id}><div className="image-setting"><select value={binding.position} onChange={e=>p.onNodeAsset({...binding,position:e.target.value as NodeAsset["position"]})}><option value="top">Above text</option><option value="bottom">Below text</option><option value="background">Background</option></select><select value={binding.objectFit} onChange={e=>p.onNodeAsset({...binding,objectFit:e.target.value as NodeAsset["objectFit"]})}><option value="contain">Fit</option><option value="cover">Fill</option></select><button onClick={()=>p.onRemoveImage(binding)}>Remove</button></div><div className="image-dimensions"><label>W<input type="number" min="40" max="900" value={binding.width} onChange={e=>{const width=Number(e.target.value);p.onNodeAsset({...binding,width,height:Math.round(width/ratio)})}}/></label><label>H<input type="number" min="30" max="700" value={binding.height} onChange={e=>{const height=Number(e.target.value);p.onNodeAsset({...binding,height,width:Math.round(height*ratio)})}}/></label><label>X<input type="range" min="0" max="100" value={binding.cropX??50} onChange={e=>p.onNodeAsset({...binding,cropX:Number(e.target.value)})}/></label><label>Y<input type="range" min="0" max="100" value={binding.cropY??50} onChange={e=>p.onNodeAsset({...binding,cropY:Number(e.target.value)})}/></label></div>{asset&&<button className="open-image" onClick={()=>p.onOpenImage(asset,binding)}>Open image</button>}</div>})}</div>
          <div className="inspector-section"><h3>Map style</h3><div className="field-pair"><label className="field-label">Theme<select value={p.doc.mindmap.theme} onChange={e=>p.onDoc({...p.doc,mindmap:{...p.doc.mindmap,theme:e.target.value as ThemeName,updatedAt:Date.now()}})}>{["dark","midnight","ocean","forest","purple","mono"].map(v=><option key={v} value={v}>{v}</option>)}</select></label><label className="field-label">Layout<select value={p.doc.mindmap.layout} onChange={e=>setLayout(e.target.value as LayoutName)}>{["mindmap","tree-right","vertical","radial"].map(v=><option key={v} value={v}>{v}</option>)}</select></label></div></div>
          {p.doc.connections.some(c=>c.sourceId===selectedNode.id||c.targetId===selectedNode.id)&&<div className="inspector-section"><h3>Connections</h3>{p.doc.connections.filter(c=>c.sourceId===selectedNode.id||c.targetId===selectedNode.id).map(c=><div className="connection-card" key={c.id}><div className="connection-setting"><input placeholder="Label" value={c.label} onChange={e=>p.onConnection({...c,label:e.target.value,updatedAt:Date.now()})}/><select value={c.style} onChange={e=>p.onConnection({...c,style:e.target.value as NodeConnection["style"],updatedAt:Date.now()})}><option value="straight">Straight</option><option value="bezier">Bezier</option><option value="elbow">Elbow</option></select><button onClick={()=>p.onDeleteConnection(c.id)}>×</button></div><ColorControl label="Line color" value={c.color} presets={CONNECTION_PALETTE} onChange={color=>p.onConnection({...c,color,updatedAt:Date.now()})}/></div>)}</div>}
          <button className="danger-text" onClick={p.onDelete}>Delete node</button>
        </> : <div className="inspector-empty"><Menu/><p>Select a node to edit its content and appearance.</p></div>}
      </aside>}
    </div>
  </main>;
}

function ColorControl({label,value,presets,onChange}:{label:string;value:string;presets:string[];onChange:(color:string)=>void}){const transparent=value==="transparent";return <div className="color-control"><div className="color-control-head"><span>{label}</span><label className="custom-color" title={`Choose custom ${label.toLowerCase()} color`}><i className={transparent?"transparent-swatch":""} style={{background:value}}/><code>{transparent?"TRANSPARENT":value.toUpperCase()}</code><input type="color" value={transparent?"#000000":value} onChange={e=>onChange(e.target.value)}/></label></div><div className="color-row"><button type="button" className={`transparent-color ${transparent?"active":""}`} onClick={()=>onChange("transparent")} aria-label={`${label}: transparent`}>{transparent&&<Check/>}</button>{presets.slice(0,7).map(color=><button key={color} type="button" style={{background:color}} className={value.toLowerCase()===color.toLowerCase()?"active":""} onClick={()=>onChange(color)} aria-label={`${label}: ${color}`}>{value.toLowerCase()===color.toLowerCase()&&<Check/>}</button>)}</div></div>}

function RichTextEditor({value,onChange}:{value:string;onChange:(value:string)=>void}){const run=(command:string,arg?:string)=>{document.execCommand(command,false,arg)};return <div className="rich-field"><span>Rich text</span><div className="rich-toolbar"><button onMouseDown={e=>{e.preventDefault();run("bold")}} aria-label="Bold"><Bold/></button><button onMouseDown={e=>{e.preventDefault();run("italic")}} aria-label="Italic"><Italic/></button><button onMouseDown={e=>{e.preventDefault();run("underline")}} aria-label="Underline"><Underline/></button><button onMouseDown={e=>{e.preventDefault();run("insertUnorderedList")}} aria-label="Bulleted list"><List/></button><button onMouseDown={e=>{e.preventDefault();run("insertOrderedList")}} aria-label="Numbered list"><ListOrdered/></button><button onMouseDown={e=>{e.preventDefault();run("formatBlock","h3")}} aria-label="Heading"><Pilcrow/></button><button onMouseDown={e=>{e.preventDefault();run("justifyLeft")}} aria-label="Align left"><AlignLeft/></button><button onMouseDown={e=>{e.preventDefault();run("justifyCenter")}} aria-label="Align center"><AlignCenter/></button><button onMouseDown={e=>{e.preventDefault();const url=prompt("Link URL");if(url)run("createLink",url)}} aria-label="Add link"><Link2/></button></div><div className="rich-text-area" contentEditable suppressContentEditableWarning dangerouslySetInnerHTML={{__html:value}} onInput={e=>onChange(e.currentTarget.innerHTML)} data-placeholder="Write formatted text…"/></div>}
